[package]
name = "planetscale-driver"
version = "0.1.0"
edition = "2021"
description = "PlanetScale Serverless Driver"
license = "MIT"

[dependencies]
ps-driver-deserializer = { path = "./deserializer", version = "0.1.1" }
anyhow = "1.0.70"
base64 = "0.21.0"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"

[dev-dependencies]
tokio = { version = "1.27.0", features = ["full"] }
