[package]
name = "planetscale-driver"
version = "0.1.0"
edition = "2021"
description = "PlanetScale Serverless Driver"
lisense = "MIT"
exclude = ["tests/*"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
deserializer = { path = "./deserializer", version = "0.1.0" }
anyhow = "1.0.70"
base64 = "0.21.0"
reqwest = "0.11.16"
serde = { version = "1.0.160", features = ["derive"] }
serde_json = "1.0.96"
