[package]
name = "ps-driver-deserializer"
version = "0.1.0"
edition = "2021"
lisense = "MIT"
description = "A proc macro to deserialize a PS driver"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.26"
syn = { version = "2.0.15", features = ["derive"] }
